# Generated by Django 4.1.6 on 2023-02-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_instituition_subject_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='questionText',
            field=models.TextField(default='tester'),
            preserve_default=False,
        ),
    ]
