# Generated by Django 4.1.6 on 2023-02-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_question_questiontext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='questionId',
            field=models.CharField(default='', editable=False, max_length=10),
        ),
    ]
