# Generated by Django 4.1.6 on 2023-02-04 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_topic_question_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomDescription', models.CharField(max_length=2000)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instituteChat', to='myapp.instituition')),
                ('members', models.ManyToManyField(related_name='comMembers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PublicQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionText', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
                ('isActive', models.BooleanField(default=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicQuestion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField(default=False)),
                ('downVotes', models.ManyToManyField(related_name='downvotes', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionReply', to='myapp.publicquestion')),
                ('replyBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to=settings.AUTH_USER_MODEL)),
                ('upvotes', models.ManyToManyField(related_name='upvotes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageText', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('MessageTags', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.institutionmessage')),
                ('messageBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomMessages', to=settings.AUTH_USER_MODEL)),
                ('reactions', models.ManyToManyField(related_name='reactions', to=settings.AUTH_USER_MODEL)),
                ('roomName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='myapp.institutionchat')),
            ],
        ),
    ]
