# Generated by Django 4.1.6 on 2023-02-04 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_institutionchat_publicquestion_questionreply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionmessage',
            name='MessageTags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.institutionmessage'),
        ),
    ]
