# Generated by Django 4.1.6 on 2023-02-05 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_institutionmessage_messagetags'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionchat',
            name='groupAdmins',
            field=models.ManyToManyField(blank=True, related_name='admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='institutionmessage',
            name='reactions',
            field=models.ManyToManyField(blank=True, related_name='reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Userverify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verify', models.CharField(max_length=2000)),
                ('resetPassword', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FileList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('timeAdded', models.DateField(auto_now=True)),
                ('downloads', models.PositiveIntegerField(default=0)),
                ('Instituition', models.ManyToManyField(related_name='fileList', to='myapp.instituition')),
            ],
        ),
    ]
