# Generated by Django 4.1.6 on 2023-02-05 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_userdata_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userverify',
            name='verify',
        ),
    ]
