# Generated by Django 4.1.6 on 2023-02-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_userverify_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicquestion',
            name='title',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
