# Generated by Django 4.1.6 on 2023-02-06 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_publicquestion_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionreply',
            name='replyText',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
