# Generated by Django 4.1.6 on 2023-02-06 23:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_questionreply_replytext'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionreply',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
