# Generated by Django 4.1.6 on 2023-02-07 15:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_questionreply_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicquestion',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
