# Generated by Django 4.1.6 on 2023-02-08 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_userverify_resetpassword'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionreply',
            options={'ordering': ('-created',)},
        ),
    ]
