# Generated by Django 4.1.6 on 2023-02-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_questionreply_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionreply',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
