# Generated by Django 4.1.6 on 2023-02-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionchat',
            name='roomDescription',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
