# Generated by Django 4.1.6 on 2023-02-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_institutionchat_roomdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionchat',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
