# Generated by Django 4.1.6 on 2023-02-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_institutionchat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituition',
            name='slug',
            field=models.SlugField(default='', editable=False, null=True),
        ),
    ]
