# Generated by Django 4.1.6 on 2023-02-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_instituition_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituition',
            name='slug',
            field=models.SlugField(default='', null=True),
        ),
    ]
