# Generated by Django 4.1.6 on 2023-02-14 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_publicquestion_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionmessage',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='institutionmessage',
            name='messageText',
            field=models.TextField(null=True),
        ),
    ]
