# Generated by Django 4.1.6 on 2023-02-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_institutionmessage_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionreply',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
