from rest_framework_simplejwt.views import TokenObtainPairView
from .serializers import MyTokenObtainPairSerializer

class MyTokenPairView(TokenObtainPairView):
    serializer_class=MyTokenObtainPairSerializer